### ISSUE TITLE
Can you release a first version as "stable"?

### ISSUE THREAD

**Issue by dizda** [norkunas/onesignal-php-api#1]
If it's stable enough of course, but it looks like ok to me.

```
$ composer require norkunas/onesignal-php-api

  [InvalidArgumentException]
  Could not find package norkunas/onesignal-php-api at any version for your minimum-s
  tability (stable). Check the package spelling or your minimum-stability
```

It would be helpful, to avoid decreasing the minimum-stability of our apps.

**Comment by norkunas** [comment]
@dizda released.

**Comment by dizda** [comment]
Thanks @norkunas :-)

FYI I just made a Symfony bundle which integrate your library: https://github.com/dizda/OnesignalApiBundle

**Comment by norkunas** [comment]
@dizda :+1:
