### ISSUE TITLE
update user data

### ISSUE THREAD

**Issue by web-ap** [norkunas/onesignal-php-api#101]
Hello,
I have users registered on OneSignal by Android. I'd like to update their tags by PHP. Is it possible to select user by Player ID (for eg), then add a tag to him using the API ?

Thanks.
Regards

**Comment by norkunas** [comment]
Hello,

If you know the device id, you could try to update it like this:
```
$tags = [
  'tag1' => 'value',
  'tag2' => 'another_value',
];

$oneSignal->devices->update('device_id', ['tags' => $tags]);
```

**Comment by web-ap** [comment]
Thanks ! It did the trick 👍
