### ISSUE TITLE
Missing "external_id" option for notifications

### ISSUE THREAD

**Issue by unexge** [norkunas/onesignal-php-api#104]
OneSignal supports [`external_id`](https://documentation.onesignal.com/reference#section-idempotency) option on creating notifications. But this option is missing in [NotificationResolver](https://github.com/norkunas/onesignal-php-api/blob/master/src/Resolver/NotificationResolver.php).

**Comment by norkunas** [comment]
Hello, could you submit a PR? :)

**Comment by unexge** [comment]
sure, i will send a PR in couple hours :)
