### ISSUE TITLE
The option "android_gcm_sender_id" does not exist.

### ISSUE THREAD

**Issue by rcerljenko** [norkunas/onesignal-php-api#111]
This starts to show up in latest release version.
API calls: `apps->add()` or `apps->update()`

**Comment by norkunas** [comment]
Very strange :disappointed:

**Comment by norkunas** [comment]
See [releases/tag/1.9.0](https://github.com/norkunas/onesignal-php-api/releases/tag/1.9.0)

**Comment by rcerljenko** [comment]
thx man  :)
