### ISSUE TITLE
Can't install onesignal-php-api

### ISSUE THREAD

**Issue by valsha** [norkunas/onesignal-php-api#112]
composer require php-http/guzzle6-adapter norkunas/onesignal-php-api

> Using version ^2.0 for php-http/guzzle6-adapter
> Using version ^1.9 for norkunas/onesignal-php-api
> ./composer.json has been created
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for norkunas/onesignal-php-api ^1.9 -> satisfiable by norkunas/onesignal-php-api[1.9.0].
>     - norkunas/onesignal-php-api 1.9.0 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
>     - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
>     - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
>     - Conclusion: don't install php-http/httplug v2.0.0
> 
> 
> Installation failed, deleting ./composer.json.

**Comment by valsha** [comment]
ok, i just try
1. composer require php-http/guzzle6-adapter
2. - Installing php-http/guzzle6-adapter (v2.0.1): Downloading (100%)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files
3. composer require norkunas/onesignal-php-api

> Using version ^1.9 for norkunas/onesignal-php-api
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for norkunas/onesignal-php-api ^1.9 -> satisfiable by norkunas/onesignal-php-api[1.9.0].
>     - Conclusion: remove php-http/httplug v2.0.0
>     - Conclusion: don't install php-http/httplug v2.0.0
>     - norkunas/onesignal-php-api 1.9.0 requires php-http/client-common ^1 -> satisfiable by php-http/client-common[1.3.0, 1.5.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, v1.0.0, v1.1.0, v1.2.0, v1.2.1, v1.4.0, v1.4.1, v1.4.2, v1.6.0].
>     - php-http/client-common v1.0.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
>     - php-http/client-common v1.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
>     - php-http/client-common v1.2.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
>     - php-http/client-common v1.2.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
>     - php-http/client-common 1.3.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common 1.5.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common 1.7.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common 1.8.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common 1.8.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common 1.8.2 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common 1.9.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common v1.4.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common v1.4.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common v1.4.2 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - php-http/client-common v1.6.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
>     - Can only install one of: php-http/httplug[v1.0.0, v2.0.0].
>     - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
>     - Installation request for php-http/httplug (locked at v2.0.0) -> satisfiable by php-http/httplug[v2.0.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by norkunas** [comment]
I'll try to investigate this tomorrow.
