### ISSUE TITLE
php-http/client-common 2.0 support

### ISSUE THREAD

**Issue by KDederichs** [norkunas/onesignal-php-api#117]
As the title says, support for php-http/client-common 2.0 would be nice to have in the long run.

**Comment by norkunas** [comment]
Do you know if it's possible to support both versions?

**Comment by KDederichs** [comment]
Seems possible yes:
https://github.com/php-http/cache-plugin/commit/561b54482003a0290e3619c095ac790c90590db9
Enables both versions on their cache plugin.
Seems like it's done through a BC Compatible trait found in the 2.x versions:
https://github.com/php-http/client-common/blob/master/src/Plugin/VersionBridgePlugin.php

**Comment by KDederichs** [comment]
But I don't think you are even using something in your bundle that would actually require any change (from what I could see while quickly looking over it) so just allowing version 2.x as well should probably work already.

**Comment by norkunas** [comment]
Want to contribute maybe? 🙂

**Comment by KDederichs** [comment]
Seems like some packages are dropping PHP 5.6 support with version 2.0 so if you want to keep that in it's probably not possible to update.

**Comment by norkunas** [comment]
I've started refactoring for v2 which uses PSR http client interface, so you could use any compatible client, but don't have time now to complete it

**Comment by NikoVonLas** [comment]
Maybe just create new package with new version of php-http/client-common and php-http/guzzle6-adapter? I dont think its good to forked this and push to composer. And i cant use vcs, this not good for another users of my package.

**Comment by norkunas** [comment]
Upgraded dependencies so client-common 2.0 should work.

**Comment by NikoVonLas** [comment]
Thank you!

пт, 19 июл. 2019 г., 9:28 Tomas Norkūnas <notifications@github.com>:
