### ISSUE TITLE
Create new notification

### ISSUE THREAD

**Issue by ivaMadDog** [norkunas/onesignal-php-api#123]
Have got an exception when trying to send a new one notification  with the next params: 'chrome_web_badge', 'chrome_web_badge_type'. The OptionsResolver class doesn't support, but OneSignal app has them.

Could you extend the current extension? Thank you.

`$this->api->notifications->add([
            'app_id' => $appId,
            'contents' => [
                'en' => $message
            ],
            'headings' => [
                'en' => $title
            ],
            'include_player_ids' => $devicesIds,
            'chrome_web_icon' => 'https://site.s3.us-east-2.amazonaws.com/users/7d6f4899287cfccc263f073558f20713b0da308c1521016853.png',
            'chrome_web_badge' => 'https://site.loc/favicon.png',
            'chrome_web_badge_type' => "image/png",
        ])`

ERROR: Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The options "chrome_web_badge", "chrome_web_badge_type" do not exist. Defined options are: "adm_big_picture", "adm_group", "adm_group_message", "adm_large_icon", "adm_small_icon", "adm_sound", "amazon_background_data", "android_accent_color", "android_background_data", "android_background_layout", "android_channel_id", "android_group", "android_group_message", "android_led_color", "android_sound", "android_visibility", "app_id", "app_ids", "big_picture", "buttons", "chrome_big_picture", "chrome_icon", "chrome_web_icon", "chrome_web_image", "collapse_id", "content_available", "contents", "data", "delayed_option", "delivery_time_of_day", "email_body", "email_from_address", "email_from_name", "email_subject", "excluded_segments", "existing_android_channel_id", "external_id", "filters", "firefox_icon", "headings", "include_amazon_reg_ids", "include_android_reg_ids", "include_chrome_reg_ids", "include_chrome_web_reg_ids", "include_external_user_ids", "include_ios_tokens", "include_player_ids", "include_wp_uris", "include_wp_wns_uris", "included_segments", "ios_attachments", "ios_badgeCount", "ios_badgeType", "ios_category", "ios_sound", "isAdm", "isAndroid", "isAnyWeb", "isChrome", "isChromeWeb", "isFirefox", "isIos", "isSafari", "isWP", "isWP_WNS", "large_icon", "mutable_content", "priority", "send_after", "small_icon", "subtitle", "summary_arg", "summary_arg_count", "template_id", "thread_id", "ttl", "url", "web_buttons", "web_push_topic", "web_url", "wp_sound", "wp_wns_sound".
 in localhost\vendor\symfony\options-resolver\OptionsResolver.php:796

**Comment by norkunas** [comment]
I'm on holidays until next week, you could contribute submitting a PR with missing options.
