### ISSUE TITLE
Create Segment via PHP API

### ISSUE THREAD

**Issue by hassaan-dev** [norkunas/onesignal-php-api#125]
Hi,
I want to create segments via API, it is possible?

I found the [this](https://github.com/norkunas/onesignal-php-api/pull/124) but any update on this?

Waiting for the response

**Comment by norkunas** [comment]
Hi, i'll try to finish it tomorrow. Until that you can use directly `request` method from `OneSignal` instance.

**Comment by norkunas** [comment]
@hassaan-dev it's finished https://github.com/norkunas/onesignal-php-api/releases/tag/v1.13.0

**Comment by hassaan-dev** [comment]
Wow thanks man.

One more question, Is paid app required for this or I can create segment for free app too?

**Comment by norkunas** [comment]
I didn't try this so i'm not sure, but documentation states:
> Requirements
A OneSignal Paid Plan

**Comment by hassaan-dev** [comment]
thanks @norkunas
