### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by xberg** [norkunas/onesignal-php-api#13]
Hi,
I don't understand how I can use this? Do I need to install anything? Are these just code examples? 
I would like to use onesignal thru wordpress with small php customisations. Am I looking in the right place?
thanks

**Comment by norkunas** [comment]
Hi @xberg,

you can install this library through composer, autoload it and then use as in examples.
If you don't know how to get started then read this section https://getcomposer.org/doc/00-intro.md

**Comment by norkunas** [comment]
Also you can download this library as a ZIP file and then load it with your custom class loader or at least you can write a simple spl autoloader with would load it
