### ISSUE TITLE
Recover the error

### ISSUE THREAD

**Issue by staffxxx** [norkunas/onesignal-php-api#130]
I wanted to recover the error so I did this
`try {
//code here
}
catch(Exception $e) {
echo $e->getMessage();
}`

`This does not show a result : Client error: `DELETE https://onesignal.com/api/v1/players/50?app_id=a20576b6-5348-4df7-a56a-26` resulted in a `400 Bad Request` response: {"errors":["No user with this id found"]}`

How to recover the response in array?

Thank you

**Comment by norkunas** [comment]
Hello,

Currently there is no way, but it will be in v2 release, until that you can parse the message and use json decode.

**Comment by staffxxx** [comment]
Thank you norkunas for your answer. Do not have a solution while waiting for version 2?

When do you think version 2 will be released

**Comment by norkunas** [comment]
Maybe before christmas :) We could update for now code to set the original exception as previous, so you could access it with request/response data. Wanna submit a PR?

**Comment by staffxxx** [comment]
I do not understand Wanna submit to PR?

**Comment by norkunas** [comment]
Do you want to contribute submitting a pull request with code changes?

**Comment by staffxxx** [comment]
Yes I want ;)

**Comment by norkunas** [comment]
I guess you aren't familiar with git? :) If that's the case you can read more about it here https://github.com/firstcontributions/first-contributions

**Comment by norkunas** [comment]
v2 is released.
