### ISSUE TITLE
error with httpClient given 

### ISSUE THREAD

**Issue by inkly** [norkunas/onesignal-php-api#131]
Hi,

I have only copied your readme for install

> composer require symfony/http-client nyholm/psr7 norkunas/onesignal-php-api

and I have this error :

> OneSignal\OneSignal::__construct() must be an instance of Http\Client\Common\HttpMethodsClient or null, instance of Symfony\Component\HttpClient\Psr18Client given

code :

`use OneSignal\Config;
use OneSignal\OneSignal;
use Symfony\Component\HttpClient\Psr18Client;
use Nyholm\Psr7\Factory\Psr17Factory;

require __DIR__ . '/../../vendor/autoload.php';

$config = new Config('***', '***', '***');
$httpClient = new Psr18Client();
$requestFactory = $streamFactory = new Psr17Factory();

$oneSignal = new OneSignal($config, $httpClient, $requestFactory, $streamFactory);`

where is my mistake ?

**Comment by norkunas** [comment]
Hello, it looks that you installed v1 while current readme is for v2.
