### ISSUE TITLE
Add field "apns_push_type_override"

### ISSUE THREAD

**Issue by valentintintin** [norkunas/onesignal-php-api#133]
Hi,

There is a change in OneSignal API for VOIP : [Issue Github](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/574)
This is the OneSignal API with the new field : [Here](https://documentation.onesignal.com/reference#section-delivery)

Here it's my temporary fix in `NotificationResolver.php` :
```
->setDefined('apns_push_type_override')
->setAllowedTypes('apns_push_type_override', 'string')
```
Can you change your code ?
Thanks a lot for your work !

Valentin

**Comment by norkunas** [comment]
Hello, maybe would you like to contribute and make pull request for this yourself? :slightly_smiling_face:

**Comment by valentintintin** [comment]
Hi, [here it is](https://github.com/norkunas/onesignal-php-api/pull/134) :)

**Comment by norkunas** [comment]
Thank you. Could you also add it to the tests? :)
