### ISSUE TITLE
Delete OneSignal app via REST API

### ISSUE THREAD

**Issue by mistris** [norkunas/onesignal-php-api#135]
Is it possible to delete an app via REST API?
Or the only way how to do it is via interface?
![image](https://user-images.githubusercontent.com/3584575/76934213-62adf580-68f7-11ea-81e0-cedf4f96cc8a.png)

**Comment by norkunas** [comment]
Hello, I'm not sure. It is not documented, so you write to OneSignal support and ask them. If they will provide some info we could implement this.
