### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by boskos-q** [norkunas/onesignal-php-api#147]
Any plans for upgrading package to support php8 ?

**Comment by norkunas** [comment]
I thought it should support,what's missing? :)

**Comment by norkunas** [comment]
Added PHP8 to CI to make this explicit :)

**Comment by boskos-q** [comment]
I'm gonna close this one, as the error was on my end for not reading carefully composer error :)
Thanks for the prompt reply tho
