### ISSUE TITLE
null value for basic_auth_key when adding app by api

### ISSUE THREAD

**Issue by spiritwebdev** [norkunas/onesignal-php-api#170]
Hi
Getting null value for basic_auth_key when adding app by api and when viewing it with view method too.
How to fix that?

**Comment by norkunas** [comment]
Hello,
What do you mean by getting null value? Probably you don't configure it?

**Comment by spiritwebdev** [comment]
Nope, onesignal now hide basic_auth_key value when you creating app by api method.
You can take it only in member area now.
