### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by victormacko** [norkunas/onesignal-php-api#179]
Symfony 7 has just come out (yay!) and it would be awesome if this package could be updated to support it?
I'm not sure if it's just going to be a case of updating the composer.json file to include SF7 or something else as well?

Thank you so much for maintaining such a great package - I use it sooo soo much!

**Comment by norkunas** [comment]
Hey, will try to do and release this asap :)

**Comment by norkunas** [comment]
Released :)

**Comment by victormacko** [comment]
Wow -- thank you @norkunas, that's an incredible response-time! Very very much appreciate all your work :D
