### ISSUE TITLE
Are there plans to upgrade this library to use guzzlehttp version 6 and higher?

### ISSUE THREAD

**Issue by malish8632** [norkunas/onesignal-php-api#19]
Currently we are using this library and AWS PHP SDK 3 and we have to use 5.3 version of guzzlehttp due to limitation of this library.
We are considering to use similar library which doesn't have this limitation but wandering if you are planning to remove this lock soon.

Thanks

**Comment by norkunas** [comment]
Hello @malish8632,

I'm considering to implement https://github.com/php-http/httplug so you will be able to use any http adapter
