### ISSUE TITLE
Dependency conflict (Guzzle)

### ISSUE THREAD

**Issue by olivernagy** [norkunas/onesignal-php-api#29]
Looks like Guzzle ~5.3 is still a dependency for this project, which creates a conflict with another library I'm using (chargify-php-sdk). Since in the README there's an option for either 6.x or 5.x, can we remove ~5.3 as a dependency?

```
$ composer require norkunas/onesignal-php-api  
Problem 1  
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.1].  
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.0].  
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.1].  
    - norkunas/onesignal-php-api v0.1.5 requires guzzlehttp/guzzle ~5.3 -> satisfiable by guzzlehttp/guzzle[5.3.0].  
    - Installation request for norkunas/onesignal-php-api ^0.1.5 -> satisfiable by norkunas/onesignal-php-api[v0.1.5].  
    - Installation request for guzzlehttp/guzzle (locked at 6.1.1) -> satisfiable by guzzlehttp/guzzle[6.1.1].
```

Thanks for the answer

**Comment by norkunas** [comment]
@olivernagy 1.0 is not released yet, so you have to install dev-master version

**Comment by liorSolcito** [comment]
Hello @norkunas ,
What i need to do exactly?
What is dev-master? i poor on composer.
Can you help me please, what i nedd to put on composer file / comand line?

Thanks!

**Comment by worldlyjohn** [comment]
@norkunas i'm getting an error on this...
`composer require norkunas/onesignal-php-api:dev-master`

**Comment by norkunas** [comment]
@worldlyjohn could you explain more what error?

**Comment by worldlyjohn** [comment]
wow thanks for quick response!

`$ composer require norkunas/onesignal-php-api:dev-master`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for norkunas/onesignal-php-api dev-master -> satisfiable by norkunas/onesignal-php-api[dev-master].
    - norkunas/onesignal-php-api dev-master requires php-http/client-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

**Comment by norkunas** [comment]
Please read readme how to setup v1 :) you need to install http-client
implementation before.

2016-12-02 17:06 "John Brennan" <notifications@github.com> rašė:
