### ISSUE TITLE
Laravel 5.1 Integration

### ISSUE THREAD

**Issue by shahin88** [norkunas/onesignal-php-api#30]
It is working standalone. 

Can I use this with laravel ? 
it is to mention that , I've tried with Laravel but it doesn't install all requirements like standalone for that reason it returns error with : Undefined namespace _Common_ and _MessageFactory_

> use Http\Client\Common\HttpMethodsClient as HttpClient;
> use Http\Message\MessageFactory\GuzzleMessageFactory;

If, then please write a note for me... 

Thank You

**Comment by norkunas** [comment]
@shahin88 hello,

Did you install the library with ```1.0.x-dev``` version?

**Comment by shahin88** [comment]
WOW; What an efficient solution. Thank you so much. :+10:

**Comment by norkunas** [comment]
No problem. :wink:
