### ISSUE TITLE
Url validation and deeplinks

### ISSUE THREAD

**Issue by dpgover** [norkunas/onesignal-php-api#33]
The url validation format does not allow for custom deeplink protocols.
I think the restriction for http/https should be removed.

Is that intended?

Cheers!

**Comment by norkunas** [comment]
Hello @dpgover,
Check #34, do you think this would be better?

**Comment by dpgover** [comment]
#34 is perfect, as validate_url doesn't care about the protocol.

Thanks!

**Comment by dpgover** [comment]
Can you merge this to v0.1.5 or make a v0.1.6 release?

Thanks!!

**Comment by norkunas** [comment]
@dpgover v0.1.6 is now released.

**Comment by dpgover** [comment]
:+1: :+1: :+1: 

Thanks!!!!
