### ISSUE TITLE
Please add TTL option

### ISSUE THREAD

**Issue by kumatozz** [norkunas/onesignal-php-api#37]
https://documentation.onesignal.com/docs/notifications-create-notification - according to the documentation there is "ttl" option, but I get the following exception:

The option "ttl" does not exist. Defined options are: "adm_big_picture", "adm_group", "adm_group_message", "adm_large_icon", "adm_small_icon", "adm_sound", "amazon_background_data", "android_accent_color", "android_background_data", "android_group", "android_group_message", "android_led_color", "android_sound", "android_visibility", "app_id", "app_ids", "big_picture", "buttons", "chrome_big_picture", "chrome_icon", "chrome_web_icon", "content_available", "contents", "data", "delayed_option", "delivery_time_of_day", "excluded_segments", "firefox_icon", "headings", "include_amazon_reg_ids", "include_android_reg_ids", "include_chrome_reg_ids", "include_chrome_web_reg_ids", "include_ios_tokens", "include_player_ids", "include_wp_uris", "include_wp_wns_uris", "included_segments", "ios_badgeCount", "ios_badgeType", "ios_sound", "isAdm", "isAndroid", "isAnyWeb", "isChrome", "isChromeWeb", "isIos", "isSafari", "isWP", "large_icon", "send_after", "small_icon", "tags", "template_id", "url", "wp_sound", "wp_wns_sound".ERROR

**Comment by norkunas** [comment]
@kumatozz thanks for the report, also I would be glad to accept a PR if you'd make it
