### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by mczernin** [norkunas/onesignal-php-api#42]
I am having huge problems using this library without composer; but i`d love to somehow use it as it`d be a huge painsaver :)
I use this instead of the autoloader:

```
function __autoload($class_name) {
  require_once("OneSignal/Config.php");
  require_once("OneSignal/Devices.php");
  require_once("OneSignal/OneSignal.php");
}
```

Now i`m getting all kinds of errors from guzzle...

**Comment by norkunas** [comment]
If you want to install without composer then you need to load the guzzle library also ;)

**Comment by mczernin** [comment]
Thanks, somehow i didn't get it to work and used my VPS instead with composer installed :)
