### ISSUE TITLE
Update Device Tags

### ISSUE THREAD

**Issue by mczernin** [norkunas/onesignal-php-api#43]
Hello again, sorry for bothering you again :)
How do i get the following to work?

`
$api->devices->update('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx', [
    'tags' => '{"foo":"bar","this":"that"}',
]);
`

somehow nothing changes when i look at device list
i also tried

`'tags' => {"foo":"bar","this":"that"}`

Best regards,
Max

**Comment by norkunas** [comment]
Hello @mczernin,

Data that you provide for update is encoded to json format at the end, so you need to provide it only in the php format like here https://github.com/norkunas/onesignal-php-api#notifications
