### ISSUE TITLE
v0.1.11 introduces BC-break

### ISSUE THREAD

**Issue by tixastronauta** [norkunas/onesignal-php-api#56]
Release ```v.0.1.11``` should be a **major** release as it introduces a bc-break. 

My previously working code, now crashes because I'm not injecting a ```Client``` into ```OneSignal``` constructor. In ```v.0.1.10``` there was no need to inject a ```Client``` because a new Guzzle Client was instantiated.

**Comment by norkunas** [comment]
@tixastronauta constructor in 0.1 doesn't changed

**Comment by tixastronauta** [comment]
@norkunas from my understanding that is not the case.

# [Constructor at 0.1.10](https://github.com/norkunas/onesignal-php-api/blob/v0.1.10/src/OneSignal.php#L43) 

```php
public function __construct(Config $config = null, Client $client = null)
{
    $this->config = ($config ?: new Config());
    $this->client = ($client ?: new Client([
        'defaults' => [
            'headers' => [
                'Accept' => 'application/json',
            ],
        ],
    ]));
}
```


# [Constructor at 0.1.11](https://github.com/norkunas/onesignal-php-api/blob/v0.1.11/src/OneSignal.php#L43)

```php
public function __construct(Config $config = null, Client $client = null)
{
    $this->config = ($config ?: new Config());
    if (null !== $client) {
        $this->client = $client;
    }
}
```

**Comment by norkunas** [comment]
@tixastronauta sorry, master was target in release. should be good now.

**Comment by tixastronauta** [comment]
Awesome @norkunas 👍 ! Thank you!
