### ISSUE TITLE
getDevice(device_id) not working -- (getting Bad Request)

### ISSUE THREAD

**Issue by seme1** [norkunas/onesignal-php-api#63]
The following does not work
$device = $api->devices->getOne('device_id');

I'm getting the following msg when the above is run:

Client error: `GET https://onesignal.com/api/v1/players/` resulted in a `400 Bad Request` response: {"errors":["app_id not found. You may be missing a Content-Type: application/json header."]}

**Comment by norkunas** [comment]
Which version are you using?

**Comment by norkunas** [comment]
@seme1 fixed it
