### ISSUE TITLE
Notifications getAll() offset > 50

### ISSUE THREAD

**Issue by raduca-adrian** [norkunas/onesignal-php-api#64]
Hi,

It seems that when I try to take all notifications using getAll() the offset can not go above 50 as the condition: ```max(0, min(self::NOTIFICATIONS_LIMIT, filter_var($offset, FILTER_VALIDATE_INT)))``` always evaluates to 50 for offset values > 50.

**Comment by norkunas** [comment]
Hello @raduca-adrian,

That's because this is the max limit which onesignal allows. For reference see [here](https://documentation.onesignal.com/reference#view-notifications).

**Comment by raduca-adrian** [comment]
Yes, but that limit refers to the number of results returned in a request, not to the offset. Using a combination of offset and limit you should be able to retrieve all notifications for an application, but in the current state, where offset can not go over 50, the results you can get is max 100, although you may have more notifications.

**Comment by norkunas** [comment]
Thank you for finding this @raduca-adrian, should be good now.

**Comment by raduca-adrian** [comment]
You're welcome! Cheers!
