### ISSUE TITLE
Follow PSR for HTTP clients

### ISSUE THREAD

**Issue by norkunas** [norkunas/onesignal-php-api#75]
https://groups.google.com/forum/#!topic/php-fig/iFZF6T9L2zA
https://github.com/php-http/fig-standards/blob/master/proposed/http-client/http-client.md

**Comment by peter279k** [comment]
I think the title should be change into: `Follow PSR-7 for HTTP clients` :+1: .
And I think we can consider and use the existed PHP package: [guzzle/psr7](https://github.com/guzzle/psr7) :smile: .
