### ISSUE TITLE
Composer depencie issue

### ISSUE THREAD

**Issue by tchauviere** [norkunas/onesignal-php-api#80]
Hi,

First of all thanks for your precious work which saved me quiet a lot of time :) 
Just wanted to let you know that as of today I tried to install your package through composer but it seems that some dependencies are missing on packagist :

![screen](https://i.imgur.com/xNyHRbh.png)

I checked on packagist.org and no package named 'php-http/client-implementation' found, don't know if its a temporary issue with packagist or the owner of the package but I thought that I'll let be aware of that.

Best regards,

**Comment by norkunas** [comment]
Hey,

I see all the providers at https://packagist.org/providers/php-http/client-implementation

As this is the virtual package, you'll need to require an adapter when installing v1

**Comment by tchauviere** [comment]
Oh, ok, I don't know why I see all the providers too by now, probs a temp issue by my side, thanks !
