### ISSUE TITLE
Regarding Config and send Notificaion using API

### ISSUE THREAD

**Issue by rameshwebmaster** [norkunas/onesignal-php-api#84]
Hello,
i have updated composer and i have following concerns

$config = new Config();
		$config->setApplicationId('your_application_id');
		$config->setApplicationAuthKey('your_application_auth_key');
		$config->setUserAuthKey('your_auth_key');

		$guzzle = new GuzzleClient([
		// ..config
		]);

		$client = new HttpClient(new GuzzleAdapter($guzzle), new GuzzleMessageFactory());
		$api = new OneSignal($config, $client);

I am new to this api. 
i have checked backend of Onesignal and they provided only REST API and Auth key but above there are three keys that need to update so i confused here which keys are for what?

Thanks,

**Comment by norkunas** [comment]
Hello @rameshwebmaster,

User auth key is used for `apps` requests, so you could create/update/view your apps and for all other endpoints app auth key is used because all other resources and directly related with your application.

**Comment by rameshwebmaster** [comment]
ok thanks,
what setting need to write in config ?
$guzzle = new GuzzleClient([
	// ..config
	]);

**Comment by norkunas** [comment]
You can use defaults or read the guzzle documentation

2017-12-11 12:54 "rameshwebmaster" <notifications@github.com> rašė:

**Comment by rameshwebmaster** [comment]
how to handle exception using this package? and how to print error to end user?
i have used this exception
catch (\OneSignal\Exception\OneSignalException  $e) { 
dd($e->getMessage());
}

**Comment by norkunas** [comment]
Looks ok.
