### ISSUE TITLE
chrome_web_image and other attribute problems

### ISSUE THREAD

**Issue by humanwere** [norkunas/onesignal-php-api#86]
Hello,

I just tested your app and realised that your app has no allow to sent notifications with allowed attributes by OneSignal. For example i need to use 'chrome_web_image '. 

The issue is `The option "chrome_web_image" does not exist. Defined options are: "adm_big_picture", "adm_large_icon", "adm_small_icon", "amazon_background_data", "android_accent_color", "android_background_data", "android_led_color", "android_sound", "android_visibility", "app_id", "big_picture", "buttons", "chrome_big_picture", "chrome_icon", "content_available", "contents", "data", "delayed_option", "delivery_time_of_day", "excluded_segments", "headings", "include_amazon_reg_ids", "include_android_reg_ids", "include_chrome_reg_ids", "include_ios_tokens", "include_player_ids", "include_wp_urls", "included_segments", "ios_badgeCount", "ios_badgeType", "ios_sound", "isAdm", "isAndroid", "isChrome", "isIos", "isWP", "large_icon", "send_after", "small_icon", "tags", "template_id", "url", "wp_sound".`

Can you solve this please?

Thanks in advance :)

**Comment by norkunas** [comment]
Hey

It's here https://github.com/norkunas/onesignal-php-api/blob/master/src/Resolver/NotificationResolver.php#L141

Which version are you using?

**Comment by humanwere** [comment]
interesting :)

Actually in my composer related line is this "dizda/onesignal-api-bundle": "^0.1.5" and the version result is;

  - Installing norkunas/onesignal-php-api (v0.1.0): Loading from cache
  - Installing dizda/onesignal-api-bundle (0.1.5): Loading from cache 

I tried to upload newer version but there is a problem with dizda's library like this;

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dizda/onesignal-api-bundle 0.1.5 requires norkunas/onesignal-php-api v0.1.0 -> satisfiable by norkunas/onesignal-php-api[v0.1.0] but these conflict with your requirements or minimum-stability.
    - dizda/onesignal-api-bundle 0.1.5 requires norkunas/onesignal-php-api v0.1.0 -> satisfiable by norkunas/onesignal-php-api[v0.1.0] but these conflict with your requirements or minimum-stability.
    - Installation request for dizda/onesignal-api-bundle ^0.1.5 -> satisfiable by dizda/onesignal-api-bundle[0.1.5].

How can I fix this? Do you have any idea?

PS: my project builted with symfony v2.8

**Comment by norkunas** [comment]
@humanwere you could try [adelplace/onesignal-bundle](https://github.com/adelplace/onesignal-bundle)

**Comment by humanwere** [comment]
Thank you @norkunas its solved.
