### ISSUE TITLE
Onesignal ID differences

### ISSUE THREAD

**Issue by johnreytanquinco** [norkunas/onesignal-php-api#89]
Apology for this simple question, but where can I get the `notificationId` when I want to call an Api to GET notification.
```
curl --include \
     --header "Authorization: Basic NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj" \
 https://onesignal.com/api/v1/notifications/{notificationId}?app_id={appId}
```

**Comment by norkunas** [comment]
When you send notification onesignal responds with notification ID.
Also you can call `https://onesignal.com/api/v1/notifications?app_id=:app_id&limit=:limit&offset=:offset` to get notifications list and then call your endpoint to get notification data which is not included in the list.

**Comment by johnreytanquinco** [comment]
yeah I see it. Thanks @norkunas ! Appreciate your fast reply!
