### ISSUE TITLE
How to achieve sending notification to more than 2000 people?

### ISSUE THREAD

**Issue by Slavezax** [norkunas/onesignal-php-api#93]
Do you have an idea to implement this feature?

**Comment by norkunas** [comment]
Hi,

So far I didn't have a chance to send so many notifications yet :) Do you mean this is limited by OneSignal itself or something is broken in the library?

**Comment by norkunas** [comment]
The way I see then is to create separate notifications because it's not library responsibility to workaround those limits :)

**Comment by peter279k** [comment]
I think it looks like a limitation of the original API service provider.

It's out of range for this PHP package. Perhaps sending the notifications are for two times to the `4000` people.
