### ISSUE TITLE
Missing 'android_gcm_sender_id' in AppResolver.php

### ISSUE THREAD

**Issue by rcerljenko** [norkunas/onesignal-php-api#94]
Missing field for creating/updating app config (type: string):
android_gcm_sender_id - Your Google Project number. Also know as Sender ID.

Solution:
```
->setDefined('android_gcm_sender_id')
->setAllowedTypes('android_gcm_sender_id', 'string')
```

Documentation:
https://documentation.onesignal.com/reference#create-an-app

**Comment by norkunas** [comment]
Hello, you could submit a PR

**Comment by rcerljenko** [comment]
Will composer automatically update new version?

________________________________

**Comment by norkunas** [comment]
Yes, it should. I've made a new release

**Comment by rcerljenko** [comment]
Supercool. Thanks!

________________________________
